dosh: set path relative to Dockerfile if --no-auto-context unset
This improves commit bedf204e628e78e67618d37fd4a3d5330a5ee6a6.

This creates the doshfile relative to the Dockerfile directory and uses
the tar's option -C to create (or to append) the context archive given
to docker-build(1) through stdin.

Fixes:

	$ dosh --dockerfile support/docker/Dockerfile
	tar: apt-sources.list: Cannot stat: No such file or directory
	tar: Exiting with failure status due to previous errors
	[+] Building 0.2s (5/14)                                                                                                                                                        docker:default
	 => [internal] load remote build context                                                                                                                                                  0.0s
	 => copy /context /                                                                                                                                                                       0.0s
	 => [internal] load metadata for docker.io/library/debian:bookworm-20250203                                                                                                               0.2s
	 => [ 1/11] FROM docker.io/library/debian:bookworm-20250203@sha256:4abf773f2a570e6873259c4e3ba16de6c6268fb571fd46ec80be7c67822823b3                                                       0.0s
	 => ERROR [ 2/11] COPY apt-sources.list /etc/apt/sources.list                                                                                                                             0.0s
	------
	 > [ 2/11] COPY apt-sources.list /etc/apt/sources.list:
	------
	doshfile:27
	--------------------
	  25 |
	  26 |     # This repository can be a bit slow at times. Don't panic...
	  27 | >>> COPY apt-sources.list /etc/apt/sources.list
	  28 |
	  29 |     # Install 32bit variant on x86_64 image.
	--------------------
	ERROR: failed to build: failed to solve: failed to compute cache key: failed to calculate checksum of ref 260d5f6d-47f3-40be-91cc-66b3995fa27d::xwkqdeiazq82rdq05930s0po8: "/apt-sources.list": not found