Fix "Add make-rpm.sh"
This fixes commit f0450287fdd416df62890c99f40156d57526012c.

Fixes:

	$ cqfd -b rpm
	realpath: .cqfd/rpm/Dockerfile: No such file or directory
	.cqfd/rpm/Dockerfile: No such Dockerfile

And, fixes:

	$ cqfd -b rpm
	error: failed to stat /home/gportay/rpmbuild/SPECS/dosh.spec: No such file or directory