docker-{shell,cqfd}: fix completion
This fixes completion by outputing words line by line instead of in a
single line. Also, this appens :0 (ShellCompDirectiveDefault[1]).

Fixes:

	$ docker cqfd sh\ ash\ dash\ bash\ ksh\ zsh\ csh\ tcsh\ fish\ init\ flavors\ exec\ run\ release\ shell\ version\ help\ -C\ -d\ -f\ -b\ -q\ --release\ -V\ --version\ -h\ --help
	Error: sh ash dash bash ksh zsh csh tcsh fish init flavors exec run release shell version help -C -d -f -b -q --release -V --version -h --help: Invalid command

	$ docker shell -c\ -s\ -i\ -o\ --dockerfile\ --platform\ --context\ --no-auto-context\ --no-extra-options\ --no-doshprofile\ --no-doshrc\ --directory\ --working-directory\ --sudo\ --root\ --dind\ --groups\ --home\ --parent\ --mount-options\ --shell\ --ls\ --gc\ --build-only\ --build\ --rebuild\ --rmi\ --detach\ --exec\ --attach\ --kill\ --rm\ --tag\ --dry-run\ --verbose\ --version\ --help\ -a\ -b\ -e\ -f\ -h\ -m\ -n\ -u\ -v\ -x\ -C
	/usr/bin/dosh: line 900: $1: unbound variable

[1]: https://github.com/spf13/cobra/blob/6dec1ae26659a130bdb4c985768d1853b0e1bc06/completions.go#L92-L95