dosh: set path relative to Dockerfile if --no-auto-context
docker-build(1) reads the Dockerfile from PATH, URL, or STDIN. It may
send a lot of data to the Docker daemon if PATH is used.

	NAME

	docker-build - Build an image from a Dockerfile

	SYNOPSIS

	docker build [--add-host[=[]]] [--build-arg[=[]]] [--cache-from[=[]]] [-c|--cpu-shares[=0]] [--cgroup-parent[=CGROUP-PARENT]] [--help] [--iidfile[=IIDFILE]] [-f|--file[=PATH/Dockerfile]]  [-squash]  Experimental  [--force-rm]  [--isolation[=default]]  [--label[=[]]]  [--no-cache]  [--pull] [--compress] [-q|--quiet] [--rm[=true]] [-t|--tag[=[]]] [-m|--memory[=MEMORY]] [--memory-swap[=LIMIT]] [--network[="default"]] [--shm-size[=SHM-SIZE]] [--cpu-period[=0]]  [--cpu-quota[=0]]  [--cpuset-cpus[=CPUSET-CPUS]]  [--cpuset-mems[=CPUSET-MEMS]] [--target[=[]]] [--ulimit[=[]]] PATH | URL | -

	DESCRIPTION

	This will read the Dockerfile from the directory specified in
	PATH. It also sends any other files and directories found in the
	current directory to the Docker daemon. The contents of this
	directory would be used by ADD commands found within the
	Dockerfile.

	Warning, this will send a lot of data to the Docker daemon
	depending on the contents of the current directory. The build is
	run by the Docker daemon, not by the CLI, so the whole context
	must be transferred to the daemon. The Docker CLI reports
	"Sending build context to Docker daemon" when the context is
	sent to the daemon.

	When the URL to a tarball archive or to a single Dockerfile is
	given, no context is sent from the client to the Docker daemon.
	In this case, the Dockerfile at the root of the archive and the
	rest of the archive will get used as the context of the build.
	When a Git repository is set as the URL, the repository is
	cloned locally and then sent as the context.

The Dockerfile instructions ADD (Add local or remote files and
directories) and COPY (Copy files and directories) reads the source
files and directories from the PATH set to docker-build(1).

This sets the docker-build's PATH positional argument relative to the
Dockerfile directory to build the image from that directory, where the
sources files and directories ADD'ed or COPY'ed should be located.

Fixes:

	$ dosh --no-auto-context --dockerfile support/docker/Dockerfile
	Info: ADD or COPY instructions sends build context to daemon.
	      Consider option --context <TAR> to speed up the build of image.
	      First, generate the context archive as suggested by the command below:
	          tar cf context.tar doshfile apt-sources.list
	      Then, run /home/gportay/.local/bin/dosh again and tell it to use the context archive:
	          /home/gportay/.local/bin/dosh --context context.tar
	[+] Building 0.8s (6/15)                                                                                                                                                        docker:default
	 => [internal] load build definition from doshfile                                                                                                                                        0.0s
	 => => transferring dockerfile: 3.93kB                                                                                                                                                    0.0s
	 => [internal] load metadata for docker.io/library/debian:bookworm-20250203                                                                                                               0.8s
	 => [internal] load .dockerignore                                                                                                                                                         0.0s
	 => => transferring context: 2B                                                                                                                                                           0.0s
	 => [internal] load build context                                                                                                                                                         0.0s
	 => => transferring context: 2B                                                                                                                                                           0.0s
	 => [ 1/11] FROM docker.io/library/debian:bookworm-20250203@sha256:4abf773f2a570e6873259c4e3ba16de6c6268fb571fd46ec80be7c67822823b3                                                       0.0s
	 => ERROR [ 2/11] COPY apt-sources.list /etc/apt/sources.list                                                                                                                             0.0s
	------
	 > [ 2/11] COPY apt-sources.list /etc/apt/sources.list:
	------
	doshfile:27
	--------------------
	  25 |
	  26 |     # This repository can be a bit slow at times. Don't panic...
	  27 | >>> COPY apt-sources.list /etc/apt/sources.list
	  28 |
	  29 |     # Install 32bit variant on x86_64 image.
	--------------------
	ERROR: failed to build: failed to solve: failed to compute cache key: failed to calculate checksum of ref 260d5f6d-47f3-40be-91cc-66b3995fa27d::tgp60rvcok4dyvm8qi5gmsmgf: "/apt-sources.list": not found